### ISSUE TITLE
Any plans/thoughts for SuperChat-like feature?

### ISSUE THREAD

**Issue by dm17** [benwilber/boltstream#2]
Pretty self explanatory. I haven't seen any self-hosted streaming solutions that could take $-contributions from the audience. Do you know of any or have plans on payment gateway connections for boltstream?
Thanks! :)

**Comment by benwilber** [comment]
No plans for that right now, but the chat backend is pluggable, so nothing prevents using whatever chat backend you want that has those kinds of features
