### ISSUE TITLE
Support for 360° video

### ISSUE THREAD

**Issue by neuhaus** [benwilber/boltstream#3]
I'd like to stream 360° video and set the HLS client to display it as 360° video also. Do you see a way to support it?

**Comment by benwilber** [comment]
Hello neuhaus, it isn't supported right now, but as far as I know there isn't anything special required in the streaming configuration.  It would need to use the VideoJS 360/VR plugin to show the correct aspect and make the video player pannable.

https://github.com/videojs/videojs-vr
