### ISSUE TITLE
Sign-Up

### ISSUE THREAD

**Issue by nitrag** [benwilber/boltstream#7]
Is there a sign-up? I can't "stream now" on demo or my local installation because it keeps going into a sign-in loop. The superuser admin account doesn't work (loop) and I can't create a regular user (missing sign-up).

**Comment by benwilber** [comment]
There's no signup view implemented on the Django app right now.  The Django app itself is pretty bare-bones at the moment, pretty much just allows logging in, creating streams via the Django admin, and then authorizing those streams for playback.

I pushed an update to create a default Django superuser (`boltstream`/`boltstream`) https://github.com/benwilber/boltstream/pull/8

From there you can go into the Django admin, create a stream, copy the stream key and use it to stream to your instance.
